<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>PHP for Web Designers</title>
<link href="styles/exercises.css" rel="stylesheet" type="text/css">
</head>

<body>
<h1>PHP for Web Designers: Exercise Files</h1>
<h2>Chapter 1: Introduction to PHP </h2>
<ul class="open">
    <li>Video 01_01: How PHP makes pages dynamic
        <ul>
            <li><a href="ch01/01_01/accordion.html" target="new">JavaScript accordion </a></li>
            <li><a href="ch01/01_01/copyright.php" target="new">Date range generated by PHP</a></li>
            <li><a href="ch01/01_01/phptime.php" target="new">Current time generated by PHP</a></li>
            <li><a href="ch01/01_01/jstime.html" target="new">Current time constantly updated by JavaScript</a></li>
            <li><a href="ch01/01_01/form.php" target="new">Conditional display after form submission</a></li>
        </ul>
    </li>
    <li>Video 01_02: How to use PHP in a web page
        <ul>
            <li><a href="ch01/01_02/copyright.php" target="new">File containing only PHP</a> (date range)</li>
            <li><a href="ch01/01_02/embed_final.php" target="new">PHP code embedded in HTML</a> (current day)</li>
        </ul>
    </li>
    <li>Video 01_04: Storing numbers and text in variables
        <ul>
            <li><a href="ch01/01_04/variables.php" target="new">Start file</a></li>
            <li><a href="ch01/01_04/variables_final.php" target="new">Values stored in variables</a></li>
        </ul>
    </li>
    <li>Video 01_05: Displaying the values of number and text variables
        <ul>
            <li><a href="ch01/01_05/display.php" target="new">Start file</a></li>
            <li><a href="ch01/01_05/display_final.php" target="new">Displaying values with echo, print, and shorthand tag</a></li>
        </ul>
    </li>
    <li>Video 01_06: Using functions to manipulate values
        <ul>
            <li><a href="ch01/01_06/functions.php" target="new">Start file</a></li>
            <li><a href="ch01/01_06/functions_final.php" target="new">Using a function to convert text to uppercase</a></li>
        </ul>
    </li>
    <li>Video 01_07: Adding comments to PHP scripts
        <ul>
            <li><a href="ch01/01_07/comments.php" target="new">Start file</a></li>
            <li><a href="ch01/01_07/comments_final.php" target="new">Different comment styles in use</a></li>
        </ul>
    </li>
</ul>
<h2>Chapter 2: Using Server-Side Includes for Common Page Elements</h2>
<ul>
    <li>Video 02_01: What are server-side includes?
        <ul>
            <li><a href="ch02/02_01/page01.php" target="new">Example of server-side include</a></li>
        </ul>
    </li>
    <li>Video 02_02: Deciding which include command to use
        <ul>
            <li><a href="ch02/02_02/include.php" target="new">Missing file with include</a></li>
            <li><a href="ch02/02_02/require.php" target="new">Missing file with require</a></li>
        </ul>
    </li>
</ul>
<h2>Chapter 3: Using Conditions to Change Page Output</h2>
<ul>
    <li>Video 03_02: Changing output depending on the current time
        <ul>
            <li><a href="ch03/03_02/date_parts.php" target="new">Start file</a></li>
            <li><a href="ch03/03_02/date_parts_final.php" target="new">Greeting according to the time of day</a></li>
        </ul>
    </li>
    <li>Video 03_03: Adjusting the server's time zone
        <ul>
            <li><a href="ch03/03_03/timezone.php" target="new">Start file</a></li>
            <li><a href="ch03/03_03/timezone_final.php" target="new">Changing the time zone with date_default_timezone_set()</a></li>
        </ul>
    </li>
</ul>
<h2>Chapter 4: Working with Multiple Values in Arrays and Loops</h2>
<ul>
    <li>Video 04_01: Storing multiple values in a variable as an array
        <ul>
            <li><a href="ch04/04_01/arrays.php" target="new">Start file</a></li>
            <li><a href="ch04/04_01/arrays_final.php" target="new">Original and shorthand array syntax</a> </li>
        </ul>
    </li>
    <li>Video 04_02: Inspecting an array's elements
        <ul>
            <li><a href="ch04/04_02/examine_array.php" target="new">Start file</a></li>
            <li><a href="ch04/04_02/examine_array_final.php" target="new">Using print_r() to inspect array</a></li>
        </ul>
    </li>
    <li>Video 04_05: Displaying an array as a comma-separated list
        <ul>
            <li><a href="ch04/04_05/join_array.php" target="new">Start file</a></li>
            <li><a href="ch04/04_05/join_array_final.php" target="new">Using implode() to convert an array to a string</a></li>
        </ul>
    </li>
    <li>Video 04_06: Looping through an array's values
        <ul>
            <li><a href="ch04/04_06/foreach_key.php" target="new">Start file</a></li>
            <li><a href="ch04/04_06/foreach_key_final.php" target="new">Using a foreach loop to display array values</a></li>
        </ul>
    </li>
    <li>Video 04_07: Labeling array elements
        <ul>
            <li><a href="ch04/04_07/associative.php" target="new">Start file</a></li>
            <li><a href="ch04/04_07/associative_final.php" target="new">Associative array</a></li>
        </ul>
    </li>
    <li>Video 04_08: Looping through an array's labels and values
        <ul>
            <li><a href="ch04/04_08/foreach_assoc.php" target="new">Start file</a></li>
            <li><a href="ch04/04_08/foreach_assoc_final.php" target="new">Using foreach to loop through an array's keys and values</a></li>
        </ul>
    </li>
    <li>Video 04_09: Finding if an element exists in an array
        <ul>
            <li><a href="ch04/04_09/in_array.php" target="new">Start file</a></li>
            <li><a href="ch04/04_09/in_array_final.php" target="new">Using in_array() to find an array element</a></li>
        </ul>
    </li>
</ul>
<h2>Chapter 5: Getting User Input from a Form</h2>
<ul>
    <li>Video 05_01: Getting form input sent by the POST method
        <ul>
            <li><a href="ch05/05_01/post.php" target="new">Start file</a></li>
            <li><a href="ch05/05_01/post_final.php" target="new">Inspecting the $_POST array</a></li>
        </ul>
    </li>
    <li>Video 05_02: Retrieving values from a URL's query string
        <ul>
            <li><a href="ch05/05_02/get.php" target="new">Start file</a></li>
            <li><a href="ch05/05_02/get_final.php" target="new">Using the $_GET array to display a value from a query string</a></li>
        </ul>
    </li>
    <li>Video 05_05: Finding and extracting a substring
        <ul>
            <li><a href="ch05/05_05/substring.php" target="new">Start file</a></li>
            <li><a href="ch05/05_05/substring_final.php" target="new">Using strpos() to find a substring and substr() to extract it</a></li>
        </ul>
    </li>
</ul>
<h2>Chapter 6: Displaying Content from a Database</h2>
<ul>
    <li>Video 06_04: Repeating output at specific intervals in a loop
        <ul>
            <li><a href="ch06/06_05/modulo_01.php" target="new">How modulo division works</a></li>
            <li><a href="ch06/06_05/modulo_02.php" target="new">Finding every fourth item</a></li>
        </ul>
    </li>
</ul>
<h2>Chapter 7: Handling Errors</h2>
<ul>
    <li>Video 07_01: Dealing with PHP errors
        <ul>
            <li><a href="ch07/07_01/syntax_error.php" target="new">Example of parse (syntax) error</a></li>
            <li><a href="ch07/07_01/include_error.php" target="new">Example of include error</a></li>
            <li><a href="ch07/07_01/configuration.php" target="new">PHP configuration</a></li>
            <li><a href="ch07/07_01/.htaccess" target="new">.htaccess file for Apache</a></li>
            <li><a href="ch07/07_01/.user.ini" target="new">.user.ini file</a></li>
        </ul>
    </li>
    <li>Video 07_02: Why is my page blank or incomplete?
        <ul>
            <li><a href="ch07/07_02/.htaccess" target="new">.htaccess file to turn off display_errors</a></li>
            <li><a href="ch07/07_02/blank.php" target="new">Blank file caused by parse (syntax) error</a></li>
            <li><a href="ch07/07_02/blank_final.php" target="new">Corrected version of blank file</a></li>
            <li><a href="ch07/07_02/incomplete.php" target="new">Truncated file caused by fatal error</a></li>
            <li><a href="ch07/07_02/incomplete_final.php" target="new">Corrected version of truncated file</a></li>
        </ul>
    </li>
    <li>Video 07_03: Tracking down parse errors
        <ul>
            <li><a href="ch07/07_03/parse_errors.php" target="new">Page with multiple syntax errors</a></li>
            <li><a href="ch07/07_03/parse_errors_final.php" target="new">Corrected version</a></li>
        </ul>
    </li>
    <li>Video 07_04: What to do with &quot;failed to open stream&quot;
        <ul>
            <li><a href="ch07/07_04/failed_stream.php" target="new">File with two &quot;failed stream&quot; errors</a></li>
            <li><a href="ch07/07_04/failed_stream_final.php" target="new">Corrected version</a></li>
        </ul>
    </li>
    <li>Video 07_05: What does &quot;headers already sent&quot; mean?
        <ul>
            <li><a href="ch07/07_05/.htaccess" target="new">.htaccess file to turn off output_buffering</a></li>
            <li><a href="ch07/07_05/bouquet.php" target="new">Build-a-bouquet</a></li>
        </ul>
    </li>
    <li>Video 07_06: What does undefined index, variable, or constant mean?
        <ul>
            <li><a href="ch07/07_06/index.php" target="new">Page with undefined variable and index</a></li>
        </ul>
    </li>
    <li>Video 07_07: What on earth is T_ENCAPSED_AND_WHITE_SPACE?
        <ul>
            <li><a href="ch07/07_07/t_encapsed.php" target="new">Page with array element in double-quoted string</a></li>
        </ul>
    </li>
</ul>
<script src="js/mainindex.js"></script>
</body>
</html>