<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Embedding PHP in HTML</title>
</head>

<body>
<h1>This is Plain HTML</h1>
<p>So is this.</p>
<p>This is HTML, but the day is generated by PHP: <?php echo date('l'); ?>.</p>
</body>
</html>